const SOLANA_COMPOSABLE_IMPORTS = [
  ["useAccountInfo", "useSolanaAccountInfo"],
  ["useAction", "useSolanaAction"],
  ["useAirdrop", "useSolanaAirdrop"],
  ["useBalance", "useSolanaBalance"],
  ["useConnection", "useSolanaConnection"],
  ["useIdentity", "useSolanaIdentity"],
  ["usePlanTransaction", "useSolanaPlanTransaction"],
  ["usePlanTransactions", "useSolanaPlanTransactions"],
  ["useProgramAccounts", "useSolanaProgramAccounts"],
  ["usePayer", "useSolanaPayer"],
  ["useRequest", "useSolanaRequest"],
  ["useRpc", "useSolanaRpc"],
  ["useSelectedWalletAccount", "useSolanaSelectedWalletAccount"],
  ["useSendTransaction", "useSolanaSendTransaction"],
  ["useSendTransactions", "useSolanaSendTransactions"],
  ["useSignIn", "useSolanaSignIn"],
  ["useSignMessage", "useSolanaSignMessage"],
  ["useSignAndSendTransaction", "useSolanaSignAndSendTransaction"],
  ["useSignTransactions", "useSolanaSignTransactions"],
  ["useSignAndSendTransactions", "useSolanaSignAndSendTransactions"],
  ["useSignatureStatus", "useSolanaSignatureStatus"],
  ["useSolana", "useSolana"],
  ["useSolanaClient", "useSolanaClient"],
  ["useSubscription", "useSolanaSubscription"],
  ["useTokenAccounts", "useSolanaTokenAccounts"],
  ["useTokenBalance", "useSolanaTokenBalance"],
  ["useTrackedData", "useSolanaTrackedData"],
  ["useTransactionConfirmation", "useSolanaTransactionConfirmation"],
  ["useWallet", "useSolanaWallet"],
  ["useWallets", "useSolanaWallets"],
] as const;

export const SOLANA_IMPORTS = SOLANA_COMPOSABLE_IMPORTS.map(([name, as]) => ({
  name,
  as,
  from: `@vue-solana/vue/${name}`,
}));
