import { defineBuildConfig } from "unbuild";

export default defineBuildConfig({
  entries: [
    "src/buffer-polyfill",
    "src/index",
    "src/useAccountInfo",
    "src/useAction",
    "src/useAirdrop",
    "src/useBalance",
    "src/useClientCapability",
    "src/useConnection",
    "src/useIdentity",
    "src/usePlanTransaction",
    "src/usePlanTransactions",
    "src/useProgramAccounts",
    "src/usePayer",
    "src/useRequest",
    "src/useRpc",
    "src/useSelectedWalletAccount",
    "src/useSendTransaction",
    "src/useSendTransactions",
    "src/useSignAndSendTransaction",
    "src/useSignAndSendTransactions",
    "src/useSignMessage",
    "src/useSignIn",
    "src/useSignTransactions",
    "src/useSignatureStatus",
    "src/useSolana",
    "src/useSolanaClient",
    "src/useSubscription",
    "src/useTokenAccounts",
    "src/useTokenBalance",
    "src/useTrackedData",
    "src/useTransaction",
    "src/useTransactionConfirmation",
    "src/useWallet",
    "src/useWallets",
    "src/swr",
    "src/kit",
  ],
  declaration: true,
  clean: true,
  rollup: {
    emitCJS: true,
  },
  externals: ["@solana/kit", "@solana/kit-plugin-rpc", "vue", /^@vue-solana\/core(?:\/.*)?$/],
});
