// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: [
    "@nuxt/ui",
    "@nuxt/content",
    "@nuxtjs/i18n",
    "@vue-solana/nuxt",
    "@vercel/analytics",
    "@nuxt/image",
    "@nuxtjs/seo",
  ],
  css: ["~/assets/css/main.css"],
  app: {
    head: {
      link: [
        { rel: "icon", type: "image/png", href: "/favicon.png" },
        { rel: "apple-touch-icon", href: "/favicon.png" },
      ],
    },
  },
  site: {
    url: "https://vue-solana-docs.vercel.app",
    name: "Vue Solana",
    description: "Documentation for Vue and Nuxt libraries that help developers use Solana.",
    defaultLocale: "en",
  },
  sitemap: {
    urls: [
      "/",
      "/es",
      "/ko",
      "/zh",
      "/agent-skill",
      "/es/agent-skill",
      "/ko/agent-skill",
      "/zh/agent-skill",
      "/concepts/clusters",
      "/es/concepts/clusters",
      "/ko/concepts/clusters",
      "/zh/concepts/clusters",
      "/concepts/solana-for-vue-developers",
      "/es/concepts/solana-for-vue-developers",
      "/ko/concepts/solana-for-vue-developers",
      "/zh/concepts/solana-for-vue-developers",
      "/examples/nuxt",
      "/es/examples/nuxt",
      "/ko/examples/nuxt",
      "/zh/examples/nuxt",
      "/examples/vue-vite",
      "/es/examples/vue-vite",
      "/ko/examples/vue-vite",
      "/zh/examples/vue-vite",
      "/getting-started",
      "/es/getting-started",
      "/ko/getting-started",
      "/zh/getting-started",
      "/guides/account-reads",
      "/es/guides/account-reads",
      "/ko/guides/account-reads",
      "/zh/guides/account-reads",
      "/guides/errors",
      "/es/guides/errors",
      "/ko/guides/errors",
      "/zh/guides/errors",
      "/guides/message-signing",
      "/es/guides/message-signing",
      "/ko/guides/message-signing",
      "/zh/guides/message-signing",
      "/guides/rpc-and-clusters",
      "/es/guides/rpc-and-clusters",
      "/ko/guides/rpc-and-clusters",
      "/zh/guides/rpc-and-clusters",
      "/guides/transactions",
      "/es/guides/transactions",
      "/ko/guides/transactions",
      "/zh/guides/transactions",
      "/guides/wallets",
      "/es/guides/wallets",
      "/ko/guides/wallets",
      "/zh/guides/wallets",
      "/packages/core",
      "/es/packages/core",
      "/ko/packages/core",
      "/zh/packages/core",
      "/packages/nuxt",
      "/es/packages/nuxt",
      "/ko/packages/nuxt",
      "/zh/packages/nuxt",
      "/packages/vue",
      "/es/packages/vue",
      "/ko/packages/vue",
      "/zh/packages/vue",
      "/roadmap",
      "/es/roadmap",
      "/ko/roadmap",
      "/zh/roadmap",
      "/troubleshooting",
      "/es/troubleshooting",
      "/ko/troubleshooting",
      "/zh/troubleshooting",
    ],
    exclude: ["/demo"],
  },
  robots: {
    disallow: ["/demo"],
    sitemap: ["/sitemap.xml"],
  },
  ogImage: {
    defaults: {
      width: 1200,
      height: 630,
    },
  },
  compatibilityDate: "2024-04-03",
  solana: {
    cluster: "devnet",
  },
  content: {
    experimental: {
      sqliteConnector: "native",
    },
  },
  i18n: {
    defaultLocale: "en",
    strategy: "prefix_except_default",
    detectBrowserLanguage: false,
    vueI18n: "./i18n.config.ts",
    locales: [
      { code: "en", name: "English", language: "en-US" },
      { code: "es", name: "Español", language: "es-ES" },
      { code: "ko", name: "한국어", language: "ko-KR" },
      { code: "zh", name: "中文", language: "zh-CN" },
    ],
  },
  routeRules: {
    "/demo": { ssr: false, prerender: false },
    "/es/demo": { ssr: false, prerender: false },
    "/ko/demo": { ssr: false, prerender: false },
    "/zh/demo": { ssr: false, prerender: false },
    "/concepts/wallets": { redirect: "/guides/wallets" },
    "/es/concepts/wallets": { redirect: "/es/guides/wallets" },
    "/ko/concepts/wallets": { redirect: "/ko/guides/wallets" },
    "/zh/concepts/wallets": { redirect: "/zh/guides/wallets" },
    "/**": { prerender: true },
  },
  vite: {
    optimizeDeps: {
      include: [
        "@vue-solana/nuxt > @solana/web3-compat > @solana/web3.js > eventemitter3",
        "@vue-solana/nuxt > @vue-solana/vue > @vue-solana/core > buffer/",
        "@vue-solana/nuxt > @vue-solana/vue > @vue-solana/core > tweetnacl",
        "@vue-solana/nuxt > @vue-solana/vue > @vue-solana/core > tweetnacl/nacl-fast.js",
      ],
      needsInterop: [
        "@vue-solana/nuxt > @solana/web3-compat > @solana/web3.js > eventemitter3",
        "@vue-solana/nuxt > @vue-solana/vue > @vue-solana/core > tweetnacl",
        "@vue-solana/nuxt > @vue-solana/vue > @vue-solana/core > tweetnacl/nacl-fast.js",
      ],
    },
    $client: {
      optimizeDeps: {
        include: [
          "@vue-solana/nuxt > @solana/web3-compat > @solana/web3.js > eventemitter3",
          "@vue-solana/nuxt > @vue-solana/vue > @vue-solana/core > buffer/",
          "@vue-solana/nuxt > @vue-solana/vue > @vue-solana/core > tweetnacl",
          "@vue-solana/nuxt > @vue-solana/vue > @vue-solana/core > tweetnacl/nacl-fast.js",
        ],
        needsInterop: [
          "@vue-solana/nuxt > @solana/web3-compat > @solana/web3.js > eventemitter3",
          "@vue-solana/nuxt > @vue-solana/vue > @vue-solana/core > tweetnacl",
          "@vue-solana/nuxt > @vue-solana/vue > @vue-solana/core > tweetnacl/nacl-fast.js",
        ],
      },
    },
  },
});
